<?xml version="1.0" ?>

<!DOCTYPE calDigi [
<!ELEMENT calDigi (section)* >
<!ATTLIST calDigi cvs_Header CDATA #REQUIRED
                     cvs_Revision CDATA #REQUIRED>
<!ELEMENT section (#PCDATA | item | section)*  >
<!ATTLIST section name CDATA #REQUIRED>
<!ELEMENT item   (#PCDATA)>
<!ATTLIST item  name CDATA #REQUIRED
                value CDATA #REQUIRED>
]>

<!--    GLAST last layer constants as of Glastrelease v2r2 for 1-7 GeV 0-5 deg
        Do not modify and check in this file without permission!
        Note that the text in the item field cannot have direct ampersands of brackets!
  -->
<calDigi cvs_Header="$Header: /nfs/slac/g/glast/ground/cvs/CalRecon/xml/CalLayer.xml,v 1.2 2003/06/09 11:33:28 berrie Exp $"
         cvs_Revision="$Revision: 1.2 $">

    <section name="lastlayer">  CAL properties
	<item name="c0"     value="-35.3747"> MeV </item>
	<item name="c1"     value="68.1653"> MeV </item>
	<item name="c2"     value="-32.4386"> MeV </item>
	<item name="c3"     value="0.9933"> MeV </item>
	<item name="b0"     value="0.793"> MeV </item>
	<item name="b1"     value="0.045"> MeV </item>
        <item name="k0"     value="-2778"> Glops </item>
        <item name="k1"     value="6576"> Glops </item>
        <item name="k2"     value="-3797"> Glops^2 </item>
    </section>

</calDigi>
